apiVersion: v1
kind: Service
metadata:
  name: eirini-persi-svc
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app.kubernetes.io/instance: eirini-persi
    app.kubernetes.io/name: eirini-persi