#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini-persi-volume-services-register
  annotations:
    kapp.k14s.io/change-group: "smb.cloudfoundry.org/service-accounts"

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: eirini-persi-volume-services-register
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eirini-persi-volume-services-register
subjects:
  - kind: ServiceAccount
    name: eirini-persi-volume-services-register
    namespace: #@ data.values.namespace
roleRef:
  kind: ClusterRole
  name: eirini-persi-volume-services-register
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: eirini-persi-volume-services-register
  annotations:
    kubernetes.io/service-account.name: eirini-persi-volume-services-register
    kapp.k14s.io/change-group: "smb.cloudfoundry.org/service-account-tokens"
    kapp.k14s.io/change-rule: "upsert after upserting smb.cloudfoundry.org/service-accounts"
type: kubernetes.io/service-account-token


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini-persi-volume-services-start
  annotations:
    kapp.k14s.io/change-group: "smb.cloudfoundry.org/service-accounts"

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: eirini-persi-volume-services-start
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eirini-persi-volume-services-start
subjects:
  - kind: ServiceAccount
    name: eirini-persi-volume-services-start
    namespace: #@ data.values.namespace
roleRef:
  kind: ClusterRole
  name: eirini-persi-volume-services-start
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: eirini-persi-volume-services-start
  annotations:
    kubernetes.io/service-account.name: eirini-persi-volume-services-start
    kapp.k14s.io/change-group: "smb.cloudfoundry.org/service-account-tokens"
    kapp.k14s.io/change-rule: "upsert after upserting smb.cloudfoundry.org/service-accounts"
type: kubernetes.io/service-account-token
