apiVersion: v1
kind: Pod
metadata:
  labels:
    run: integration-test-reader
  name: integration-test-reader
  namespace: cf-workloads
spec:
  containers:
    - command:
        - sleep
      args:
        - "3600"
      image: dperson/samba
      securityContext:
        privileged: true
      imagePullPolicy: Always
      name: integration-test-reader

