# This k8s config launches an smb server and a corresponding k8s service so that it
# can be reached with k8s DNS.  To mount a share, invoke the following from within
# the k8s network:
#
# mkdir /mnt/smb
# mount -t cifs -o user=user,pass=pass //smb1.default/share /mnt/smb

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-smb1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-smb1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-smb1
    spec:
      containers:
      - command:
          - /sbin/tini
          - --
          - /usr/bin/samba.sh
          - -p
          - -u
          - user;pass
          - -s
          - share;/export;no;no;no;user
          - -p
          - -S
        image: dperson/samba
        imagePullPolicy: Always
        name: test-smb1
        ports:
          - containerPort: 139
            protocol: TCP
          - containerPort: 445
            protocol: TCP
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: smb1
spec:
  type: ClusterIP
  ports:
    - port: 445
      targetPort: 445
      protocol: TCP
      name: smb
    - port: 139
      targetPort: 139
      protocol: TCP
      name: smblegacy
  selector:
    app.kubernetes.io/name: test-smb1
