apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dev
    cloudfoundry.org/source_type: APP
  name: dev
  namespace: cf-workloads
spec:
  containers:
    - command:
        - bash
      args:
        - -c
        - echo hello > /instance1/foo; sleep 3600
      image: ubuntu
      securityContext:
        privileged: true
      imagePullPolicy: Always
      name: dev
      env:
        - name: "VCAP_SERVICES"
          value: '{"eirini-persi": [{ "credentials": { "volume_id": "instance1" }, "label": "eirini-persi", "name": "instance1", "plan": "Existing", "tags": [], "volume_mounts": [ { "container_dir": "/instance1", "device_type": "shared", "mode": "rw" } ] } ] }'
