#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.logforwarder.fullname
  labels:
    app: #@ data.values.logforwarder.fullname

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: create-pv
rules:
  - apiGroups: ["v1", ""]
    resources: ["events"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-forwarder-pv-roles
subjects:
  - kind: ServiceAccount
    name: #@ data.values.logforwarder.fullname
    namespace: #@ data.values.namespace
roleRef:
  kind: ClusterRole
  name: create-pv
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: create-pvc
  namespace: #@ data.values.targetNamespace
rules:
  - apiGroups: ["v1", ""]
    resources: ["events"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-forwarder-pvc-roles
subjects:
  - kind: ServiceAccount
    name: #@ data.values.logforwarder.fullname
    namespace: #@ data.values.namespace
roleRef:
  kind: Role
  name: create-pvc
  namespace: #@ data.values.targetNamespace
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: create-secret
  namespace: #@ data.values.targetNamespace
rules:
  - apiGroups: ["v1", ""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-forwarder-secret-roles
  namespace: #@ data.values.targetNamespace
subjects:
  - kind: ServiceAccount
    name: #@ data.values.logforwarder.fullname
    namespace: #@ data.values.namespace
roleRef:
  kind: Role
  name: create-secret
  apiGroup: rbac.authorization.k8s.io
  namespace: #@ data.values.targetNamespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.logforwarder.fullname
spec:
  replicas: #@ data.values.replicaCount
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ data.values.logforwarder.name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ data.values.logforwarder.name
    spec:
      serviceAccountName: #@ data.values.logforwarder.fullname
      automountServiceAccountToken: true
      containers:
        - name: log-forwarder
          image: #@ data.values.image.repository + ":" + data.values.image.tag
          imagePullPolicy: #@ data.values.image.pullPolicy
          env:
            - name: TARGET_NAMESPACE
              value: #@ data.values.targetNamespace
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
